
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA IDENTIFIER L_BRACE L_BRACKET NUMBER RAIZ RCOSENO RDIVISION RINVRESO RMOD RMULTIPLICACION RPOTENCIA RRESTA RSENO RSUMA RTANGENTE R_BRACE R_BRACKET STRINGinit : L_BRACEobject : L_BRACE properties R_BRACEproperties : propertyproperties : property COMMA propertiesproperty : STRING COLON valuevalue : objectvalue : arrayvalue : STRINGvalue : NUMBERarray : L_BRACKET elements R_BRACKETarray : L_BRACKET elements COMMA R_BRACKETelements : valueelements : value COMMA elements'
    
_lr_action_items = {'L_BRACE':([0,],[2,]),'$end':([1,2,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> L_BRACE','init',1,'p_init','Analizador_main.py',81),
  ('object -> L_BRACE properties R_BRACE','object',3,'p_object','Analizador_main.py',86),
  ('properties -> property','properties',1,'p_properties_single','Analizador_main.py',90),
  ('properties -> property COMMA properties','properties',3,'p_properties_multi','Analizador_main.py',94),
  ('property -> STRING COLON value','property',3,'p_property','Analizador_main.py',98),
  ('value -> object','value',1,'p_value_object','Analizador_main.py',102),
  ('value -> array','value',1,'p_value_array','Analizador_main.py',106),
  ('value -> STRING','value',1,'p_value_string','Analizador_main.py',110),
  ('value -> NUMBER','value',1,'p_value_number','Analizador_main.py',114),
  ('array -> L_BRACKET elements R_BRACKET','array',3,'p_array_single','Analizador_main.py',118),
  ('array -> L_BRACKET elements COMMA R_BRACKET','array',4,'p_array_multi','Analizador_main.py',122),
  ('elements -> value','elements',1,'p_elements_single','Analizador_main.py',126),
  ('elements -> value COMMA elements','elements',3,'p_elements_multi','Analizador_main.py',130),
]
